mailServer:
  host: smtp.gmail.com
  port: 587
  email: haikvph14059@fpt.edu.vn
  password: jjqi fskh hcho pzcn
  protocol: smtp
  isSSL: false

frontend:
    base-endpoint: http://localhost:3000

backend:
  base-endpoint: http://localhost:8080
